<?php
/*
Plugin Name: Shopp Referrers
Version: 1.0.0
Description: Shopp Referrers list all of the referrs link generated by Shopp.
Plugin URI: http://www.tinyelk.com
Author: tinyElk Studios
Author URI: http://www.tinyelk.com

	This plugin is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This plugin is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this plugin.  If not, see <http://www.gnu.org/licenses/>.
*/
if(!defined('ABSPATH')) die();

$ShoppReferrers = new ShoppReferrers();

class ShoppReferrers{
	var $product = 'shopp-referrers';

	function __construct(){
		//default stuff
		register_activation_hook(__FILE__, array(&$this, 'on_activation'));

		add_action('admin_menu', array($this, 'add_menu'), 99);
	}

	function notices(){
		if(!is_plugin_active('shopp/Shopp.php')){
			echo '<div class="error"><p><strong>Shopp Referrers</strong>: It is highly recommended to have the <a href="http://www.shopplugin.net">Shopp Plugin</a> active before using any of the Shopp Toolbox plugins.</p></div>';
		}
	}

	function toolbox_menu_exist(){
        global $menu;

        $return = false;
        foreach($menu as $menus => $item){
            if($item[0] == 'Shopp Toolbox'){
                $return = true;
            }
        }
        return $return;
    }

	function add_menu(){
		global $menu;
		$position = 52;
		while (isset($menu[$position])) $position++;

		if(!$this->toolbox_menu_exist()){
			add_menu_page('Shopp Toolbox', 'Shopp Toolbox', 'shopp_menu', 'shopp-toolbox', array('ShoppToolbox_Welcome', 'display_welcome'), plugin_dir_url(__FILE__) . 'img/toolbox.png', $position);
			$page = add_submenu_page('shopp-toolbox', 'Shopp Toolbox', 'Welcome', 'shopp_menu', 'shopp-toolbox', array('ShoppToolbox_Welcome', 'display_welcome'));
		}

		$page = add_submenu_page('shopp-toolbox', 'Shopp Referrer', 'Shopp Referrer', 'shopp_menu', $this->product, array(&$this, 'display_settings'));
		add_meta_box('shopp_referrer_list', 'Referrers List', array($this, 'display_options'), $page, 'normal', 'default');
	}

	function on_activation(){
	}

	function display_options(){
		global $wpdb;

		$results = $wpdb->get_results('SELECT data FROM '.$wpdb->prefix.'shopp_purchase WHERE data LIKE \'%Referrer%\';');
		$referrers = array();

		foreach($results as $order){
			$raw = unserialize($order->data);

			$referrers[] = $raw['Referrer'];
		}

		$uniques = array_count_values($referrers);
		arsort($uniques);

		if(!empty($uniques)):
?>
		<table>
			<?php foreach($uniques as $key => $count): ?>
				<tr>
					<td><?php echo esc_attr($key); ?></td>
					<td><strong><?php echo absint($count); ?></strong></td>
				</tr>
			<?php endforeach; ?>
		</table>
<?php else: ?>
		<p>There are currently no referrs listed.</p>
<?php
		endif;
	}

	function display_settings(){
?>

		<div id="<?php echo esc_attr($this->product); ?>" class="wrap">
	        <h2>Shopp Referrers</h2>
	        <div class="description">
	        </div>
	        <div class="messages"></div>
			<form action="" method="post">
              		<div id="poststuff" class="metabox-holder has-right-sidebar">
              			<div id="side-info-column" class="inner-sidebar">
							<?php do_meta_boxes('shopp-toolbox_page_'.$this->product, 'side', null); ?>
						</div>

						<div id="post-body" class="has-sidebar">
						<div id="post-body-content" class="has-sidebar-content">
							<div id="titlediv">
								<div class="inside">
									<?php do_meta_boxes('shopp-toolbox_page_'.$this->product, 'normal', null); ?>
								</div>
							</div>
						</div>
						</div>

					</div>
                <?php wp_nonce_field('nonce_save_settings', 'stb_referrers_nonce'); ?>

		    </form>
	    </div>
<?php
	}
}
